
# EXAMPLE CONFIGURATION.YAML, IT CONTAINS ALL THE NECESSARY LINES YOU NEED IN YOUR OWN CONFIGURATION.YAML
# DO NOT USE THIS FILE!!!!!

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages/

frontend:
  themes: !include_dir_merge_named themes/

browser_mod:

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    delay_time: 0
    trigger_time: 100
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    disarm_after_trigger: false

lovelace:
  mode: storage
  dashboards:
    homekit-infused:
      mode: yaml
      title: Homekit Infused
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: homekit-infused.yaml